name: Build and Push Container

on:
  push:
    branches: [ main ]
    paths:
      - 'Containerfile'
      - 'nginx.conf'
      - 'index.html'
      - 'index.css'
      - 'index.js'
      - 'team.json'
      - 'servizi.json'
      - 'analytics-ads.js'
      - 'img/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
